name: HyenaDNA_clone2
channels:
  - defaults
dependencies:
  - defaults/linux-64::_libgcc_mutex==0.1=main
  - defaults/linux-64::blas==1.0=mkl
  - conda-forge/linux-64::ca-certificates==2025.1.31=hbcca054_0
  - defaults/linux-64::ld_impl_linux-64==2.40=h12ee557_0
  - defaults/linux-64::libgfortran5==11.2.0=h1234567_1
  - defaults/linux-64::libstdcxx-ng==11.2.0=h1234567_1
  - defaults/noarch::tzdata==2025a=h04d1e81_0
  - defaults/linux-64::libgfortran-ng==11.2.0=h00389a5_1
  - defaults/linux-64::libgomp==11.2.0=h1234567_1
  - defaults/linux-64::_openmp_mutex==5.1=1_gnu
  - defaults/linux-64::libgcc-ng==11.2.0=h1234567_1
  - defaults/linux-64::bzip2==1.0.8=h5eee18b_6
  - defaults/linux-64::libffi==3.4.4=h6a678d5_1
  - defaults/linux-64::libsodium==1.0.18=h7b6447c_0
  - defaults/linux-64::libuuid==1.41.5=h5eee18b_0
  - defaults/linux-64::ncurses==6.4=h6a678d5_0
  - defaults/linux-64::openssl==3.0.15=h5eee18b_0
  - defaults/linux-64::tbb==2021.8.0=hdb19cb5_0
  - defaults/linux-64::xz==5.4.6=h5eee18b_1
  - conda-forge/linux-64::yaml==0.2.5=h7f98852_2
  - defaults/linux-64::zlib==1.2.13=h5eee18b_1
  - defaults/linux-64::intel-openmp==2023.1.0=hdb19cb5_46306
  - defaults/linux-64::readline==8.2=h5eee18b_0
  - defaults/linux-64::tk==8.6.14=h39e8969_0
  - defaults/linux-64::zeromq==4.3.5=h6a678d5_0
  - defaults/linux-64::mkl==2023.1.0=h213fc3f_46344
  - defaults/linux-64::sqlite==3.45.3=h5eee18b_0
  - defaults/linux-64::python==3.10.16=he870216_1
  - defaults/noarch::asttokens==2.0.5=pyhd3eb1b0_0
  - defaults/linux-64::debugpy==1.8.11=py310h6a678d5_0
  - defaults/noarch::decorator==5.1.1=pyhd3eb1b0_0
  - defaults/linux-64::exceptiongroup==1.2.0=py310h06a4308_0
  - defaults/noarch::executing==0.8.3=pyhd3eb1b0_0
  - defaults/linux-64::mkl-service==2.4.0=py310h5eee18b_2
  - defaults/linux-64::nest-asyncio==1.6.0=py310h06a4308_0
  - defaults/linux-64::packaging==24.2=py310h06a4308_0
  - defaults/linux-64::parso==0.8.4=py310h06a4308_0
  - defaults/linux-64::platformdirs==3.10.0=py310h06a4308_0
  - defaults/linux-64::psutil==5.9.0=py310h5eee18b_1
  - defaults/noarch::ptyprocess==0.7.0=pyhd3eb1b0_2
  - defaults/noarch::pure_eval==0.2.2=pyhd3eb1b0_0
  - defaults/linux-64::pygments==2.15.1=py310h06a4308_1
  - defaults/linux-64::python-dateutil==2.9.0post0=py310h06a4308_2
  - defaults/noarch::python-tzdata==2023.3=pyhd3eb1b0_0
  - conda-forge/noarch::pyyaml==6.0.2=pyhe1237c8_2
  - defaults/linux-64::pyzmq==26.2.0=py310h6a678d5_0
  - defaults/linux-64::setuptools==75.8.0=py310h06a4308_0
  - defaults/linux-64::tornado==6.4.2=py310h5eee18b_0
  - defaults/linux-64::traitlets==5.14.3=py310h06a4308_0
  - defaults/linux-64::typing_extensions==4.12.2=py310h06a4308_0
  - defaults/noarch::wcwidth==0.2.5=pyhd3eb1b0_0
  - defaults/linux-64::wheel==0.45.1=py310h06a4308_0
  - defaults/linux-64::comm==0.2.1=py310h06a4308_0
  - defaults/linux-64::jedi==0.19.2=py310h06a4308_0
  - defaults/linux-64::jupyter_core==5.7.2=py310h06a4308_0
  - defaults/linux-64::matplotlib-inline==0.1.6=py310h06a4308_0
  - defaults/noarch::pexpect==4.8.0=pyhd3eb1b0_3
  - defaults/linux-64::pip==25.0=py310h06a4308_0
  - defaults/linux-64::prompt-toolkit==3.0.43=py310h06a4308_0
  - defaults/noarch::stack_data==0.2.0=pyhd3eb1b0_0
  - defaults/linux-64::jupyter_client==8.6.3=py310h06a4308_0
  - defaults/noarch::prompt_toolkit==3.0.43=hd3eb1b0_0
  - defaults/linux-64::ipython==8.30.0=py310h06a4308_0
  - conda-forge/noarch::ipykernel==6.29.5=pyh3099207_0
  - defaults/linux-64::bottleneck==1.4.2=py310ha9d4c09_0
  - defaults/linux-64::mkl_fft==1.3.11=py310h5eee18b_0
  - defaults/linux-64::mkl_random==1.2.8=py310h1128e8f_0
  - defaults/linux-64::numpy==1.26.4=py310h5f9d8c6_0
  - defaults/linux-64::numexpr==2.10.1=py310h3c60e43_0
  - defaults/linux-64::scipy==1.15.1=py310h5f9d8c6_0
  - defaults/linux-64::pandas==2.2.3=py310h6a678d5_0
prefix: /home/mcb/users/jgu13/.conda/envs/HyenaDNA_clone2
